In [1]:
import time
import numpy as np
import pandas as pd
from sqlalchemy import create_engine
from pyecharts.charts import Bar3D
from pyecharts.commons.utils import JsCode
import pyecharts.options as opts
import os
os.chdir(r'D:\赵祎琳大信球\1')
sheet_names=['2015','2016','2017','2018','会员等级']
sheet_dict=pd.read_excel(r'D:\赵祎琳大信球\1\diagram\sales.xlsx',sheet_name=sheet_names)
sheet_dict

{'2015':               会员ID         订单号       提交日期    订单金额
 0      15278002468  3000304681 2015-01-01   499.0
 1      39236378972  3000305791 2015-01-01  2588.0
 2      38722039578  3000641787 2015-01-01   498.0
 3      11049640063  3000798913 2015-01-01  1572.0
 4      35038752292  3000821546 2015-01-01    10.1
 ...            ...         ...        ...     ...
 30769  39368100847  4281994827 2015-12-31   828.0
 30770       409757  4282010457 2015-12-31   199.0
 30771  38380526114  4282017675 2015-12-31   208.0
 30772     28074988  4282019440 2015-12-31    89.0
 30773  39460363230  4282025309 2015-12-31   719.0

 [30774 rows x 4 columns],
 '2016':               会员ID         订单号       提交日期     订单金额
 0      39288120141  4282025766 2016-01-01    76.00
 1      39293812118  4282037929 2016-01-01  7599.00
 2      27596340905  4282038740 2016-01-01   802.00
 3      15111475509  4282043819 2016-01-01    65.00
 4      38896594001  4282051044 2016-01-01    95.00
 ...            ...         ...        ...      ...
 41273  35336052906  4324910145 2016-12-31    99.00
 41274  39305835721  4324910148 2016-12-31   238.89
 41275  39296945352  4324910770 2016-12-31   765.00
 41276  14791026234  4324911025 2016-12-31    45.80
 41277  16779755770  4324911048 2016-12-31   119.00

 [41278 rows x 4 columns],
 '2017':               会员ID         订单号       提交日期    订单金额
 0      38765290840  4324911135 2017-01-01  1799.0
 1      39305832102  4324911213 2017-01-01   369.0
 2      34190994969  4324911251 2017-01-01   189.0
 3      38986333210  4324911283 2017-01-01   169.0
 4          4271359  4324911355 2017-01-01    78.0
 ...            ...         ...        ...     ...
 50834  39155833075  4338762307 2017-12-31    96.0
 50835  29523124076  4338762514 2017-12-31    99.0
 50836      7807573  4338762906 2017-12-31   258.0
 50837  36642530033  4338762958 2017-12-31   286.0
 50838  39155901156  4338763879 2017-12-31   249.0

 [50839 rows x 4 columns],
 '2018':               会员ID         订单号       提交日期    订单金额
 0      39229691808  4338764262 2018-01-01  3646.0
 1      39293668916  4338764363 2018-01-01  3999.0
 2      35059646224  4338764376 2018-01-01    10.1
 3          1084397  4338770013 2018-01-01   828.0
 4          3349915  4338770121 2018-01-01  3758.0
 ...            ...         ...        ...     ...
 81344  39229485704  4354225182 2018-12-31   249.0
 81345  39229021075  4354225188 2018-12-31    89.0
 81346  39288976750  4354230034 2018-12-31    48.5
 81347     26772630  4354230163 2018-12-31  3196.0
 81348  39455580335  4354235084 2018-12-31  2999.0

 [81349 rows x 4 columns],
 '会员等级':                会员ID  会员等级
 0            100090     3
 1       10012905801     1
 2       10012935109     1
 3       10013498043     1
 4       10014087899     4
 ...             ...   ...
 154380       998138     3
 154381       998298     1
 154382       998571     4
 154383       999563     4
 154384       999951     1

 [154385 rows x 2 columns]}

In [7]:
for i in sheet_names:
    print(i)
    print(sheet_dict[i].info())
    print(sheet_dict[i].describe())
for i in sheet_names[:-1]:
    sheet_dict[i]=sheet_dict[i].dropna()
    sheet_dict[i]=sheet_dict[i][sheet_dict[i]['订单金额']>1]
    sheet_dict[i]['max_year_date']=sheet_dict[i]['提交日期'].max()
for i in sheet_names:
    print(i)
    print(sheet_dict[i].info())
    print(sheet_dict[i].describe())

2015
<class 'pandas.core.frame.DataFrame'>
Int64Index: 30574 entries, 0 to 30773
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   会员ID    30574 non-null  int64
 1   订单号     30574 non-null  int64
 2   提交日期    30574 non-null  datetime64[ns]
 3   订单金额    30574 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 1.2 MB
None
               会员ID           订单号           订单金额
count  3.057400e+04  3.057400e+04   30574.000000
mean   2.921327e+10  4.020442e+09     967.270965
std    1.384598e+10  2.630518e+08    2073.397861
min    2.670000e+02  3.000305e+09       1.500000
25%    1.961657e+10  3.885746e+09      59.700000
50%    3.754532e+10  4.117491e+09     142.000000
75%    3.923630e+10  4.234853e+09     899.000000
max    3.954613e+10  4.282025e+09  111750.000000
2016
<class 'pandas.core.frame.DataFrame'>
Int64Index: 41001 entries, 0 to 41277
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   会员ID    41001 non-null  int64
 1   订单号     41001 non-null  int64
 2   提交日期    41001 non-null  datetime64[ns]
 3   订单金额    41001 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 1.6 MB
None
               会员ID           订单号           订单金额
count  4.100100e+04  4.100100e+04   41001.000000
mean   2.910772e+10  4.313582e+09     963.542790
std    1.388571e+10  1.094832e+07    2485.642632
min    8.100000e+01  4.282026e+09       1.500000
25%    1.943201e+10  4.309457e+09      65.000000
50%    3.740237e+10  4.317545e+09     149.000000
75%    3.923184e+10  4.321133e+09     898.000000
max    3.954554e+10  4.324911e+09  174900.000000
2017
<class 'pandas.core.frame.DataFrame'>
Int64Index: 50451 entries, 0 to 50838
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   会员ID    50451 non-null  int64
 1   订单号     50451 non-null  int64
 2   提交日期    50451 non-null  datetime64[ns]
 3   订单金额    50451 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 1.9 MB
None
               会员ID           订单号           订单金额
count  5.045100e+04  5.045100e+04   50451.000000
mean   2.884214e+10  4.332469e+09     970.990793
std    1.408666e+10  4.404894e+06    2185.446995
min    2.780000e+02  4.324911e+09       1.500000
25%    1.870549e+10  4.328416e+09      65.000000
50%    3.692362e+10  4.331989e+09     155.000000
75%    3.923070e+10  4.337528e+09     899.000000
max    3.954554e+10  4.338764e+09  123609.000000
2018
<class 'pandas.core.frame.DataFrame'>
Int64Index: 80801 entries, 0 to 81348
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   会员ID    80801 non-null  int64
 1   订单号     80801 non-null  int64
 2   提交日期    80801 non-null  datetime64[ns]
 3   订单金额    80801 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 3.1 MB
None
               会员ID           订单号           订单金额
count  8.080100e+04  8.080100e+04   80801.000000
mean   2.905571e+10  4.348372e+09     973.119528
std    1.402185e+10  4.185250e+06    2210.983968
min    2.780000e+02  4.338764e+09       1.500000
25%    1.919622e+10  4.345654e+09      68.000000
50%    3.749326e+10  4.349448e+09     151.700000
75%    3.923398e+10  4.351641e+09     925.000000
max    3.954614e+10  4.354235e+09  174900.000000
会员等级
<class 'pandas.core.frame.DataFrame'>
Int64Index: 154385 entries, 0 to 154384
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   会员ID    154385 non-null  int64
 1   会员等级    154385 non-null  int64
dtypes: int64(2)
memory usage: 3.5 MB
None
               会员ID           会员等级
count  1.543850e+05  154385.000000
mean   2.980055e+10       2.259701
std    1.365654e+10       1.346408
min    8.100000e+01       1.000000
25%    2.213894e+10       1.000000
50%    3.833022e+10       2.000000
75%    3.927932e+10       3.000000
max    3.954614e+10       5.000000
2015
<class 'pandas.core.frame.DataFrame'>
Int64Index: 30574 entries, 0 to 30773
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   会员ID           30574 non-null  int64
 1   订单号            30574 non-null  int64
 2   提交日期           30574 non-null  datetime64[ns]
 3   订单金额           30574 non-null  float64
 4   max_year_date  30574 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2)
memory usage: 1.4 MB
None
               会员ID           订单号           订单金额
count  3.057400e+04  3.057400e+04   30574.000000
mean   2.921327e+10  4.020442e+09     967.270965
std    1.384598e+10  2.630518e+08    2073.397861
min    2.670000e+02  3.000305e+09       1.500000
25%    1.961657e+10  3.885746e+09      59.700000
50%    3.754532e+10  4.117491e+09     142.000000
75%    3.923630e+10  4.234853e+09     899.000000
max    3.954613e+10  4.282025e+09  111750.000000
2016
<class 'pandas.core.frame.DataFrame'>
Int64Index: 41001 entries, 0 to 41277
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   会员ID           41001 non-null  int64
 1   订单号            41001 non-null  int64
 2   提交日期           41001 non-null  datetime64[ns]
 3   订单金额           41001 non-null  float64
 4   max_year_date  41001 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2)
memory usage: 1.9 MB
None
               会员ID           订单号           订单金额
count  4.100100e+04  4.100100e+04   41001.000000
mean   2.910772e+10  4.313582e+09     963.542790
std    1.388571e+10  1.094832e+07    2485.642632
min    8.100000e+01  4.282026e+09       1.500000
25%    1.943201e+10  4.309457e+09      65.000000
50%    3.740237e+10  4.317545e+09     149.000000
75%    3.923184e+10  4.321133e+09     898.000000
max    3.954554e+10  4.324911e+09  174900.000000
2017
<class 'pandas.core.frame.DataFrame'>
Int64Index: 50451 entries, 0 to 50838
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   会员ID           50451 non-null  int64
 1   订单号            50451 non-null  int64
 2   提交日期           50451 non-null  datetime64[ns]
 3   订单金额           50451 non-null  float64
 4   max_year_date  50451 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2)
memory usage: 2.3 MB
None
               会员ID           订单号           订单金额
count  5.045100e+04  5.045100e+04   50451.000000
mean   2.884214e+10  4.332469e+09     970.990793
std    1.408666e+10  4.404894e+06    2185.446995
min    2.780000e+02  4.324911e+09       1.500000
25%    1.870549e+10  4.328416e+09      65.000000
50%    3.692362e+10  4.331989e+09     155.000000
75%    3.923070e+10  4.337528e+09     899.000000
max    3.954554e+10  4.338764e+09  123609.000000
2018
<class 'pandas.core.frame.DataFrame'>
Int64Index: 80801 entries, 0 to 81348
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   会员ID           80801 non-null  int64
 1   订单号            80801 non-null  int64
 2   提交日期           80801 non-null  datetime64[ns]
 3   订单金额           80801 non-null  float64
 4   max_year_date  80801 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2)
memory usage: 3.7 MB
None
               会员ID           订单号           订单金额
count  8.080100e+04  8.080100e+04   80801.000000
mean   2.905571e+10  4.348372e+09     973.119528
std    1.402185e+10  4.185250e+06    2210.983968
min    2.780000e+02  4.338764e+09       1.500000
25%    1.919622e+10  4.345654e+09      68.000000
50%    3.749326e+10  4.349448e+09     151.700000
75%    3.923398e+10  4.351641e+09     925.000000
max    3.954614e+10  4.354235e+09  174900.000000
会员等级
<class 'pandas.core.frame.DataFrame'>
Int64Index: 154385 entries, 0 to 154384
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   会员ID    154385 non-null  int64
 1   会员等级    154385 non-null  int64
dtypes: int64(2)
memory usage: 3.5 MB
None
               会员ID           会员等级
count  1.543850e+05  154385.000000
mean   2.980055e+10       2.259701
std    1.365654e+10       1.346408
min    8.100000e+01       1.000000
25%    2.213894e+10       1.000000
50%    3.833022e+10       2.000000
75%    3.927932e+10       3.000000
max    3.954614e+10       5.000000

In [29]:
df_marge=pd.concat(list(sheet_dict.values())[:-1],ignore_index=True)
df_marge['year']=df_marge['提交日期'].dt.year
df_marge['date_interval']=df_marge['max_year_date']-df_marge['提交日期']
df_marge['date_interval']=df_marge['date_interval'].dt.days
rfm_df=df_marge.groupby(['会员ID','year'],as_index=False).agg({
    '订单号':'count',
    '订单金额':'sum',
    'date_interval':'min'
})
rfm_df.columns=['会员ID','year','f','m','r']
rfm_df.describe().T

,count,mean,std,min,25%,50%,75%,max
会员ID,148591.0,2.811669e+10,1.477660e+10,81.0,1.728262e+10,3.689151e+10,3.923337e+10,3.954614e+10
year,148591.0,2.016773e+03,1.129317e+00,2015.0,2.016000e+03,2.017000e+03,2.018000e+03,2.018000e+03
f,148591.0,1.365002e+00,2.626953e+00,1.0,1.000000e+00,1.000000e+00,1.000000e+00,1.300000e+02
m,148591.0,1.323741e+03,3.753907e+03,1.5,6.900000e+01,1.890000e+02,1.199000e+03,2.062518e+05
r,148591.0,1.655240e+02,1.019885e+02,0.0,7.900000e+01,1.560000e+02,2.550000e+02,3.650000e+02

In [38]:
f_bins=[0,2,5,130]
r_bins=[-1,79,255,365]
m_bins=[0,69,1199,206252]
rfm_df['f_label']=pd.cut(rfm_df['f'],bins=f_bins,labels=[i for i in range(1,len(f_bins))])
rfm_df['m_label']=pd.cut(rfm_df['m'],bins=m_bins,labels=[i for i in range(1,len(m_bins))])
rfm_df['r_label']=pd.cut(rfm_df['r'],bins=r_bins,labels=[i for i in range(len(r_bins)-1,0,-1)])

               会员ID  year  f       m    r f_label m_label r_label
0                81  2016  2   159.1    2       1       2       3
1               267  2015  2   105.0  197       1       2       2
2               278  2016  2   548.5    2       1       2       3
3               278  2017  3  7137.0   67       2       3       3
4               278  2018  1    49.9   36       1       1       3
...             ...   ... ..     ...  ...     ...     ...     ...
148586  39545536113  2016  1  2399.0  254       1       3       2
148587  39545538296  2017  1   375.0  279       1       2       1
148588  39546132904  2015  1   149.7  316       1       2       1
148589  39546134364  2015  1    49.0  242       1       1       2
148590  39546136285  2018  1    19.9  163       1       1       2

[148591 rows x 8 columns]

In [43]:
rfm_df['f_label']=rfm_df['f_label'].astype(str)
rfm_df['m_label']=rfm_df['m_label'].astype(str)
rfm_df['r_label']=rfm_df['r_label'].astype(str)
rfm_df['rfm_group']=rfm_df['r_label']+rfm_df['f_label']+rfm_df['m_label']
rfm_df['rfm_group']
rfm_df.to_excel(r'diagram\sale_rfm_group1.xlsx',index=False)

In [51]:
display_data=rfm_df.groupby(['rfm_group','year'],as_index=False).agg({'会员ID':'count'})
display_data.columns=['rfm_group','year','number']
range_color = ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf',
               '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']

range_max = int(display_data['number'].max())
c = (
    Bar3D()
    .add(
        "",
        [d.tolist() for d in display_data.values],#数据
        xaxis3d_opts=opts.Axis3DOpts(type_="category", name='分组名称'),
        yaxis3d_opts=opts.Axis3DOpts(type_="category", name='年份'),
        zaxis3d_opts=opts.Axis3DOpts(type_="value", name='会员数量'),
    )
    .set_global_opts( 
        visualmap_opts=opts.VisualMapOpts(max_=range_max, range_color=range_color), 
        title_opts=opts.TitleOpts(title="RFM分组结果"),
)
c.render()